# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bookstore
      MYSQL_DATABASE: book_store
    ports:
      - 3307:3306
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8088:8088
    depends_on:
      - db
    command:
      - ./main
      - api
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: bookstore
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DBNAME: book_store